### PR TITLE
Update the MXE build instructions (adding QtSvg)

### PR DESCRIPTION
**Pull request by woutersj**
This PR adds QtSvg to the list of software to be installed via MXE. I also had to install `python3-mako` and didn't need to change the Python alternative. I simplified the git commands.

### CODE REVIEW

**Comment by da-liii** [comment]
LGTM. I need to verify your changes step by step manually and then approve it. Thanks for your pull request.

**Comment by woutersj** [comment]
I forgot to add that I got an error about compiling gcc11 from MXE. I had to use the gcc8 with `MXE_PLUGIN_DIRS=plugins/gcc8`. Maybe this will get fixed in MXE, so I don't know if that should be in this doc. I am using Ubuntu 20.04.

File: src/build-using-cmake-and-mxe-on-wsl.tm [hunk 1]
```diff
@@ -14,30 +14,25 @@
...
+    cd $HOME/github/mxe/
 
-    git init
-
-    git remote add origin https://github.com/mxe/mxe.git
-
-    git fetch origin
-
-    git checkout master
+    git clone https://github.com/mxe/mxe.git
```
Comment (da-liii) [inline src/build-using-cmake-and-mxe-on-wsl.tm:35]: I use `git fetch` here because `git clone` fails occasionally in China. A user who has already known about `git clone` can learn about how to survive under a network chaos using git fetch.

File: src/build-using-cmake-and-mxe-on-wsl.tm [hunk 2]
```diff
@@ -87,17 +72,11 @@
...
-    git init
-
-    git remote add origin https://github.com/texmacs/texmacs.git
+    mkdir -p $HOME/github/texmacs/
 
-    git fetch origin
+    cd $HOME/github/texmacs/
 
-    git checkout master
+    git clone https://github.com/texmacs/texmacs.git
```
Comment (da-liii) [inline src/build-using-cmake-and-mxe-on-wsl.tm:89]: same above

File: src/build-using-cmake-and-mxe-on-wsl.tm (hunk 1 above)
Comment (da-liii) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: For example, to clone the android git repo, if you use git clone, you might fail because of the network issue, using git fetch, just fetch again and again, you will finally success. But if you use git clone, you might never success.

File: src/build-using-cmake-and-mxe-on-wsl.tm [hunk 3]
```diff
@@ -14,30 +14,25 @@
 
   There are three major steps to build <TeXmacs> on WSL:
 
-  <section*|Step 1. Install Ubuntu 18.04 on Windows 10>
+  <section*|Step 1. Install Ubuntu on Windows 10>
```
Comment (da-liii) [inline src/build-using-cmake-and-mxe-on-wsl.tm]: If you tested it in Ubuntu 20.04, just keep the version. Because it works on Ubuntu 20.04, does not mean it works on Ubuntu 18.04

**Comment by da-liii** [comment]
Here is error by gcc11:
```
../../guile-1.8.8/libguile/gc-segment.c: In function 'scm_i_find_heap_segment_containing_object':
../../guile-1.8.8/libguile/gc-segment.c:413:3: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  413 |   if ((scm_t_cell* ) obj < lowest_cell || (scm_t_cell*) obj >= highest_cell)
      |   ^~
../../guile-1.8.8/libguile/gc-segment.c:417:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  417 |     {
      |     ^
cc1: all warnings being treated as errors

```

**Comment by da-liii** [comment]
Please document `MXE_PLUGIN_DIRS=plugins/gcc8` in this pull request or let us wait for the fix from the upstream.

Or we may pin the version of the cloned mxe repo. I think a Github Action would be better than the easy-to-be-outdated note.

**Comment by mgubi** [comment]
what is the status of this PR?

**Comment by da-liii** [comment]
There is only 1 commit, I'm waiting for @woutersj 's response and then move on.

**Comment by mgubi** [comment]
@woutersj do you want to update it, so that it can be merged? 
If you need some help on it let me know.

File: src/build-using-cmake-and-mxe-on-wsl.tm (hunk 1 above)
Comment (woutersj) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: From some of the comments [here](https://stackoverflow.com/questions/3954852/how-to-complete-a-git-clone-for-a-big-project-on-an-unstable-connection), it seems that `git fetch` can suffer from the same problem. Shallow cloning is the top suggestion. I have left your approach as a comment and linked to this article.

**Comment by woutersj** [comment]
I've added the Ubuntu version and the `MXE_PLUGIN_DIRS` now.

File: src/build-using-cmake-and-mxe-on-wsl.tm (hunk 1 above)
Comment (da-liii) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: Not a big issue for most of the Github users. It is just a taste of mine based on the unstable network I'm suffering.

I think the final solution is that creating a Git host server in a decentralized way just like Mastodon.

Comment (woutersj) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: Federated git forges would be awesome! Forgefed is going in that direction. Forgejo seems to be implementing it. Yet another reason to move to Codeberg 🙂

Comment (da-liii) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: Forgejo sounds like an Esperanto name.

Comment (da-liii) [reply src/build-using-cmake-and-mxe-on-wsl.tm:35]: Thanks, that's exactly what I need.
